version: "3"
services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./database-backup/database_ddl.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./database-backup/menu_items.sql:/docker-entrypoint-initdb.d/2.sql"
    ports:
      - "3306:3306"
